fix: TargetPercentPipeAlgo.exec_cancel error when next_trading_date is pd.NaT
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[36], line 6
      3 from zipline.utils.algo_instance import get_algo_instance, set_algo_instance
      5 set_algo_instance(st)
----> 6 stats = st.run()
 
File c:\ProgramData\miniconda3\envs\factorlib\Lib\site-packages\zipline\algorithm.py:701, in TradingAlgorithm.run(self, data_portal)
    699 try:
    700     perfs = []
--> 701     for perf in self.get_generator():
    702         perfs.append(perf)
    704     # convert perf dict to pandas dataframe
 
File c:\ProgramData\miniconda3\envs\factorlib\Lib\site-packages\zipline\gens\tradesimulation.py:248, in AlgorithmSimulator.transform(self)
    246     self.simulation_dt = dt
    247     algo.on_dt_changed(dt)
--> 248     algo.before_trading_start(self.current_data)
    249 elif action == MINUTE_END:
    250     minute_msg = self._get_minute_message(
    251         dt,
    252         algo,
    253         metrics_tracker,
    254     )
 
File c:\ProgramData\miniconda3\envs\factorlib\Lib\site-packages\zipline\algo\basic_algo.py:315, in BasicAlgo.before_trading_start(self, data)
    307 self._in_before_trading_start = True
    309 with handle_non_market_minutes(
    310     data
    311 ) if self.data_frequency == "minute" else ExitStack():
    312 
    313     # 這邊不可用self._before_trading_start(self, data)，因為這是在底層類別下定義的
    314     # （這代表_before_trading_start是bound method，不需要手動傳遞self參數），而非使用者自定義。
--> 315     self._before_trading_start(data)
    317 self._in_before_trading_start = False
 
File c:\ProgramData\miniconda3\envs\factorlib\Lib\site-packages\zipline\algo\pipeline_algo.py:635, in TargetPercentPipeAlgo._before_trading_start(self, data)
    632 # deal with current_bar
    633 if self.order_filling_policy=='current_bar':
--> 635     self.exec_cancel(data)
    637     if self.rebalance_date_rule is not None:
    638         """
    639         Because `self.rebalance_date_rule.should_trigger` will only be triggered during trading hours (9:01-13:00),
    640         and the `before_trading_start` phase occurs at 8:45, we are modifying the hour and minute components of
    641         `get_datetime` accordingly.
    642         """
 
File c:\ProgramData\miniconda3\envs\factorlib\Lib\site-packages\zipline\algo\pipeline_algo.py:515, in TargetPercentPipeAlgo.exec_cancel(self, data)
    510 for i in open_orders[asset]:
    511     next_trading_date = self.calculate_next_trading_date(self.trading_calendar,
    512                                                          i.created.strftime('%Y-%m-%d'),
    513                                                          self.cancel_datedelta)
--> 515     if self.get_datetime().strftime('%Y-%m-%d')>=next_trading_date.strftime('%Y-%m-%d'):
    517         self.cancel_order(i)
    519         str_log = """
    520               Cancel_order: current time: {},
    521               due to : created>=current time + cancel_datedelta({} days),
   (...)
    528                                  i.filled
    529                                 )
 
File c:\ProgramData\miniconda3\envs\factorlib\Lib\site-packages\pandas\_libs\tslibs\nattype.pyx:59, in pandas._libs.tslibs.nattype._make_error_func.f()


ValueError: NaTType does not support strftime